import options from '../configuration';
import { writeFileAsync } from 'ags/file';
import { SystemUtilities } from '../lib/system/SystemUtilities';
import { CONFIG_DIR, ensureHyprlandSource, ensureParentDir } from '../lib/session/api';
import { startOnce } from '../services/startOnce';
import type { Opt } from '../lib/options';

/**
 * Central manager for Hyprland configuration throughout the application
 *
 * @remarks
 * This manager **does not** overwrite the user's main Hyprland config.
 * Instead, it generates an **overlay** config file under a stable XDG path
 * and makes the user's Hyprland config `source = <overlay>` when integration is enabled.
 *
 * The overlay file only contains settings that are:
 * 1) marked with `exports.hyprland = true`
 * 2) and (optionally) gated by a sibling `<id>_enable` / `<id>_enabled` toggle
 *
 * If integration is disabled, the overlay file is written as a harmless no-op file.
 */
class HyprlandManager {
  /**
   * Path to the generated Hyprland overlay configuration.
   *
   * @remarks
   * Uses XDG config dir so it is:
   * - stable across reboots/sessions
   * - independent from package install location (no SRC_DIR dependency)
   * - user-specific
   */
  private readonly _hypr_config_path = `${CONFIG_DIR}/hyprland.overlay.conf`;

  /**
   * Kept to preserve the existing class structure naming.
   *
   * @remarks
   * In this overlay approach, "template" is the final generated file.
   */
  private readonly _template_path = this._hypr_config_path;

  constructor() {
    // cheap constructor: no IO/monitors/timers
  }

  public get templatePath(): string {
    return this._template_path;
  }

  /**
   * Applies current Hyprland options by generating and writing the overlay config,
   * then reloading Hyprland so changes take effect.
   */
  public async applyHyprland(): Promise<void> {
    try {
      const enabled = options.hyprland.enable.get();

      // If the user disables integration:
      // - we keep the overlay file valid but harmless (no overrides)
      // - we reload Hyprland to remove any previously applied overrides
      //
      // We do NOT remove the injected `source =` line automatically; instead we
      // make the sourced file a no-op, which is safe and reversible.
      if (!enabled) {
        await writeFileAsync(this._template_path, '# AGS Hyprland integration disabled\n');
        await this._applyHyprland();
        return;
      }

      // If integration is enabled (including toggled at runtime), ensure the user's
      // config is sourcing the overlay file. The helper should be idempotent.
      ensureHyprlandSource(this._template_path);

      // Generate the overlay config statements.
      // Only "enabled" settings are emitted into the overlay file.
      const overlayLines = await this._generateVariables();

      // Persist the overlay file (this is the only file we write).
      await this._createHyprlandVarConf(overlayLines);

      // Reload Hyprland so it re-reads the sourced overlay file.
      await this._applyHyprland();
    } catch (error) {
      console.error(error);
    }
  }

  /**
   * Collects all options that are marked as Hyprland-exportable.
   *
   * @returns Array of options where `exports.hyprland === true`
   */
  public getHyprlandOptions(): Opt[] {
    const optArray = options.toArray();
    const hyprlandOptArray = optArray.filter(e => e.exports.hyprland);
    return hyprlandOptArray;
  }

  /**
   * Generates a Hyprland overlay configuration (not variable declarations).
   *
   * @remarks
   * This method converts options into Hyprland `section { key = value }` blocks.
   * Each exported Hyprland option is emitted only if it passes two conditions:
   *
   * 1) Its option id can be parsed into `hyprland.<section>.<key...>`
   * 2) Its sibling enable toggle is true, if such a toggle exists:
   *    - `<id>_enable` OR `<id>_enabled`
   *
   * Example options:
   * - hyprland.general.gaps_in        (exports.hyprland = true)
   * - hyprland.general.gaps_in_enable (true)
   *
   * Output overlay:
   * general {
   *   gaps_in = 15
   * }
   *
   * @returns Lines of the final overlay file content.
   */
  private async _generateVariables(): Promise<string[]> {
    const lines: string[] = [];
    lines.push('# generated by AGS (do not edit)');
    lines.push('');

    // Build a lookup map so we can find enable toggles quickly.
    const all = options.toArray();
    const byId = new Map<string, Opt>(all.map(o => [o.id, o]));

    // Only options explicitly marked for hypr export are considered.
    const hyprOpts = this.getHyprlandOptions();

    // Group output by Hyprland section.
    // sectionMap: "general" -> ["  gaps_in = 15", "  gaps_out = 20"]
    const sectionMap = new Map<string, string[]>();

    for (const opt of hyprOpts) {
      // Parse the option id into a Hyprland section/key pair.
      // If the id doesn't match the convention, skip it.
      const parsed = this._parseHyprOptionId(opt.id);
      if (!parsed) continue;

      // Gate each setting behind its per-setting enable toggle (if present).
      // This is what makes "no overrides unless enabled" possible.
      if (!this._isSettingEnabled(opt.id, byId)) continue;

      const { section, key } = parsed;

      // Normalize values into a Hyprland-friendly string.
      const value = this._formatHyprlandValue(opt.get());

      if (!sectionMap.has(section)) sectionMap.set(section, []);
      sectionMap.get(section)!.push(`  ${key} = ${value}`);
    }

    // Emit each section block.
    for (const [section, entries] of sectionMap.entries()) {
      if (entries.length === 0) continue;
      lines.push(`${section} {`);
      lines.push(...entries);
      lines.push('}');
      lines.push('');
    }

    // If nothing is enabled, write a harmless overlay file.
    if (sectionMap.size === 0) {
      lines.push('# (no hypr overrides enabled)');
      lines.push('');
    }

    return lines;
  }

  /**
   * Determines whether a given Hyprland-exported option should be emitted.
   *
   * @remarks
   * Per-setting enable toggles are optional:
   * - If `<id>_enable` / `<id>_enabled` exists and is false -> omit the setting
   * - If no toggle exists -> include the setting (backward compatible)
   *
   * @param valueId - id of the Hyprland-exported option (e.g. "hyprland.general.gaps_in")
   * @param byId - map of all options by id for quick lookup
   */
  private _isSettingEnabled(valueId: string, byId: Map<string, Opt>): boolean {
    const enableOpt = (byId.get(`${valueId}_enable`)) as Opt | undefined;

    if (!enableOpt) return true;
    return Boolean(enableOpt.get());
  }

  /**
   * Parses an option id into a Hyprland section and key.
   *
   * @remarks
   * Expected ids:
   * - "hyprland.<section>.<key...>"
   * - "hypr.<section>.<key...>" (alias)
   *
   * Keys are formed by joining the remaining path segments with underscores,
   * which matches common Hyprland naming conventions.
   *
   * @param id - option id to parse
   * @returns section/key pair, or null if the id doesn't match the convention
   */
  private _parseHyprOptionId(id: string): { section: string; key: string } | null {
    const parts = id.split('.');
    if (parts.length < 3) return null;

    if (parts[0] !== 'hyprland' && parts[0] !== 'hypr') return null;

    const section = parts[1];
    const key = parts.slice(2).join('_');

    return { section, key };
  }

  /**
   * Formats arbitrary option values into Hyprland config-friendly strings.
   *
   * @remarks
   * - numbers -> "12"
   * - booleans -> "1" / "0"
   * - strings -> unchanged (allows passing raw hypr expressions)
   * - objects -> JSON string (fallback)
   */
  private _formatHyprlandValue(value: unknown): string {
    if (typeof value === 'number') return String(value);
    if (typeof value === 'boolean') return value ? '1' : '0';
    if (typeof value === 'string') return value;

    try {
      return JSON.stringify(value);
    } catch {
      return String(value);
    }
  }

  /**
   * Writes the generated overlay configuration to disk.
   *
   * @param hyprLines - array of config lines (already formatted)
   */
  private async _createHyprlandVarConf(hyprLines: string[]): Promise<void> {
    await writeFileAsync(this._template_path, hyprLines.join('\n'));
  }

  /**
   * Reloads Hyprland so it re-reads the user's config (and the sourced overlay).
   */
  private async _applyHyprland(): Promise<void> {
    await SystemUtilities.sh(['hyprctl', 'reload']);
  }
}

let _hyprlandManager: HyprlandManager | null = null;

export function getHyprlandManager(): HyprlandManager {
  if (!_hyprlandManager) _hyprlandManager = new HyprlandManager();
  return _hyprlandManager;
}

/**
 * Explicit Hyprland runtime boot.
 * This was previously executed at import-time (including top-level await).
 */
export const bootHyprland = startOnce(async () => {
  const hyprlandManager = getHyprlandManager();

  // Ensure output directory exists before writing overlay files.
  ensureParentDir(hyprlandManager.templatePath);

  // Preserve previous behavior: if enabled at startup, ensure user's config sources the overlay.
  if (options.hyprland.enable.get()) {
    ensureHyprlandSource(hyprlandManager.templatePath);
  }

  // Build a lookup map once so we can discover `<id>_enable/_enabled` toggles for watchers.
  const all = options.toArray();
  const byId = new Map(all.map((o) => [o.id, o]));

  // Watch only Hypr-exportable value options by default.
  const valueIds = hyprlandManager.getHyprlandOptions().map((e) => e.id);

  // Also watch per-setting enable flags if they exist so toggles regenerate the overlay.
  const enableIds: string[] = [];
  for (const id of valueIds) {
    const a = `${id}_enable`;
    const b = `${id}_enabled`;
    if (byId.has(a)) enableIds.push(a);
    else if (byId.has(b)) enableIds.push(b);
  }

  // Watch the global integration toggle too (if it exists).
  const globalEnableId = 'hyprland.enable';

  const watchIds = Array.from(
    new Set([
      ...valueIds,
      ...enableIds,
      ...(byId.has(globalEnableId) ? [globalEnableId] : []),
    ]),
  );

  // Re-generate overlay and reload Hyprland whenever any relevant option changes.
  options.handler(watchIds, hyprlandManager.applyHyprland.bind(hyprlandManager));

  // Apply once at startup.
  await hyprlandManager.applyHyprland();
});
