import Gio from "gi://Gio?version=2.0";
import GLib from "gi://GLib?version=2.0";

// -----------------------------
// Session paths/constants
// (no import-time IO, no timers, no monitors, no global mutation)
// -----------------------------

export const USER = GLib.get_user_name();

export const CONFIG_DIR = `${GLib.get_user_config_dir()}/ALI`;
export const CONFIG_FILE = `${CONFIG_DIR}/config.json`;

// Source checkout path used by style hot-reload + icon lookup.
export const SRC_DIR = `${GLib.get_user_config_dir()}/ags/src`;

export const CACHE = `${GLib.get_user_cache_dir()}/ALI`;
export const TMP = `${GLib.get_tmp_dir()}/ALI`;

export const ICON_DIR = `${SRC_DIR}/assets`;

// -----------------------------
// Helpers (call-time IO is fine; no import-time effects)
// -----------------------------

export function ensureDirectory(dir: string): void {
  // mkdir -p semantics
  GLib.mkdir_with_parents(dir, 0o755);
}

export function ensureParentDir(filePath: string): void {
  const dir = GLib.path_get_dirname(filePath);
  ensureDirectory(dir);
}

export function fileExists(path: string): boolean {
  return GLib.file_test(path, GLib.FileTest.EXISTS);
}

/**
 * Ensure a file exists, creating parent directories if needed.
 * No-op if the file already exists.
 */
export function ensureFile(path: string): void {
  const file = Gio.File.new_for_path(path);
  const parent = file.get_parent();

  try {
    if (parent && !parent.query_exists(null)) {
      parent.make_directory_with_parents(null);
    }

    if (!file.query_exists(null)) {
      file.create(Gio.FileCreateFlags.NONE, null);
    }
  } catch (e) {
    console.error("ensureFile:", e);
  }
}

/**
 * Inject a `source = <path>` line into the user's Hyprland config if missing.
 * Idempotent.
 */
export function ensureHyprlandSource(path: string): void {
  const hyprPath = `${GLib.get_user_config_dir()}/hypr/hyprland.conf`;
  const hyprFile = Gio.File.new_for_path(hyprPath);
  const sourceLine = `\nsource = ${path}`;
  const injectText = `\n#Autogenerated By Ali Config${sourceLine}`;

  try {
    const [, rawContent] = hyprFile.load_contents(null);
    const content = new TextDecoder().decode(rawContent).trimEnd();

    if (!content.includes(sourceLine.trim())) {
      const newContent = content + "\n" + injectText;
      const [success] = hyprFile.replace_contents(
        new TextEncoder().encode(newContent),
        null,
        false,
        Gio.FileCreateFlags.REPLACE_DESTINATION,
        null,
      );

      if (!success) throw new Error("Failed to save Hyprland config");
    }
  } catch (error) {
    console.error("ensureHyprlandSource:", error);
  }
}

/**
 * Copies a file from srcPath to dstPath.
 * Ensures the destination parent directory exists.
 */
export function copyFile(srcPath: string, dstPath: string, overwrite = true): void {
  ensureParentDir(dstPath);

  const src = Gio.File.new_for_path(srcPath);
  const dst = Gio.File.new_for_path(dstPath);

  const flags = overwrite ? Gio.FileCopyFlags.OVERWRITE : Gio.FileCopyFlags.NONE;
  try {
    src.copy(dst, flags, null, null);
  } catch (e) {
    console.error("copyFile:", e);
  }
}

/**
 * Deletes a file if it exists. No-op on missing files.
 */
export function deleteFile(path: string): void {
  const file = Gio.File.new_for_path(path);
  try {
    if (file.query_exists(null)) file.delete(null);
  } catch (e) {
    console.error("deleteFile:", e);
  }
}
