import app from "ags/gtk4/app";
import Gio from "gi://Gio?version=2.0";
import GLib from "gi://GLib?version=2.0";

export function ensureDirectory(path: string): void {
    if (!GLib.file_test(path, GLib.FileTest.EXISTS)) {
        Gio.File.new_for_path(path).make_directory_with_parents(null);
    }
}

export function ensureJsonFile(path: string): void {
    const file = Gio.File.new_for_path(path);
    const parent = file.get_parent();

    if (parent && !parent.query_exists(null)) {
        parent.make_directory_with_parents(null);
    }

    if (!file.query_exists(null)) {
        const stream = file.create(Gio.FileCreateFlags.NONE, null);
        stream.write_all('{}', null);
    }
}

export function ensureHyprlandSource(path: string): void {
    const hyprPath = `${GLib.get_user_config_dir()}/hypr/hyprland.conf`;
    const Hyprfile = Gio.File.new_for_path(hyprPath);
    const sourceLine = `\nsource = ${path}`;
    const injectText = "\n#Autogenerated By Ali Config" + sourceLine

    try {
        const [, rawContent] = Hyprfile.load_contents(null);
        const content = new TextDecoder().decode(rawContent).trimEnd();

        if (!content.includes(sourceLine.trim())) {
            const newContent = content + '\n' + injectText;
            const [success] = Hyprfile.replace_contents(
                new TextEncoder().encode(newContent),
                null,
                false,
                Gio.FileCreateFlags.REPLACE_DESTINATION,
                null
            );

            if (!success) {
                throw new Error('Failed to save Hyprland config');
            }
        }
    } catch (error) {
        console.error('ensureHyprlandSource:', error);
    }
}

function ensureFile(path: string): void {
    const file = Gio.File.new_for_path(path);
    const parent = file.get_parent();

    if (parent && !parent.query_exists(null)) {
        parent.make_directory_with_parents(null);
    }

    if (!file.query_exists(null)) {
        file.create(Gio.FileCreateFlags.NONE, null);
    }
}

const CONFIG_DIR = GLib.get_user_config_dir() + '/ALI';
const CONFIG_FILE = CONFIG_DIR + '/config.json';
const SRC_DIR = GLib.get_user_config_dir() + '/ags/src'
const CACHE = GLib.get_user_cache_dir() + '/ALI';
const TMP = GLib.get_tmp_dir() + '/ALI';
const USER = GLib.get_user_name();

declare global {
    const CONFIG_DIR: string;
    const CONFIG_FILE: string;
    const SRC_DIR: string;
    const CACHE: string;
    const TMP: string;
    const USER: string;
}

Object.assign(globalThis, {
    CONFIG_DIR: CONFIG_DIR,
    CONFIG_FILE: CONFIG_FILE,
    SRC_DIR: SRC_DIR,
    CACHE: CACHE,
    TMP: TMP,
    USER: USER,
});

ensureDirectory(TMP);
ensureDirectory(CACHE);
ensureFile(CONFIG_FILE);
app.add_icons(`${SRC_DIR}/assets`);
